name: 'Terraform Apply'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  create-bucket:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        working-directory: './tf'

      - name: Check and Apply
        run: |
          BUCKET_NAME="cjtantay-dot-com-bucket"
          if aws s3api head-bucket --bucket $BUCKET_NAME --region us-east-1 2>/dev/null; then
            echo "Bucket exists."
          else
            echo "Creating bucket..."
            terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          fi
        working-directory: './tf'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

  empty_s3_bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Empty S3 Bucket
        run: |
          BUCKET_NAME="cjtantay-dot-com-bucket"
          aws s3 rm s3://$BUCKET_NAME --recursive

  build_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

  upload_project:
    runs-on: ubuntu-latest
    needs: [create-bucket, empty_s3_bucket, build_project]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Build and Upload
        run: |
          BUCKET_NAME="cjtantay-dot-com-bucket"
          aws s3 sync ./build s3://$BUCKET_NAME
