name: 'Terraform Apply'

on:
  workflow_call:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v3

      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
        working-directory: './tf'

      - name: Check and Apply
        run: |
          BUCKET_NAME="cjtantay-dot-com-bucket"
          if aws s3api head-bucket --bucket $BUCKET_NAME --region us-east-1 2>/dev/null; then
            echo "Bucket exists."
          else
            echo "Creation..."
            terraform apply -auto-approve \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_KEY }}"
          fi
        working-directory: './tf'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
